[package]
name = "lambda-rust"
version = "1.0.0"
edition = "2021"

[dependencies]
lambda_http = "0.7.0"
tokio = { version = "1.21.2", features = ["macros"] }
serde = "1.0.147"

[dev-dependencies]
maplit = "1.0.2"